spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Student_One_Card_System # Moved the database name into the URI for simplicity

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: musocs7@gmail.com
    password: MuSOCS14$
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day in milliseconds
      refresh-token:
        expiration: 604800000 # 7 days in milliseconds
